name: build

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: commaai/agnos-firmware
        path: agnos-firmware
        token: ${{ secrets.SUBMODULE_TOKEN }}
        persist-credentials: true

    - name: checkout submodule ref
      run: git submodule update --init

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - run: ./build_kernel.sh
    - run: ./build_system.sh
