name: build

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && github.run_id || github.head_ref || github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: build kernel and system
    runs-on: namespace-profile-arm64-8x16-2004-caching
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        submodules: true

    - name: Get commit message
      run: |
        {
          echo 'LAST_COMMIT_MESSAGE<<EOF'
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "${{ github.event.head_commit.message }}"
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            COMMIT_URL=$(echo "${{ github.event.repository.commits_url }}" | sed "s|{/sha}|/${{ github.sha }}|")
            echo "$(curl -s "$COMMIT_URL" | jq -r '.commit.message')"
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            PR_COMMIT_URL=$(echo "${{ github.event.repository.commits_url }}" | sed "s|{/sha}|/${{ github.event.pull_request.head.sha }}|")
            echo "$(curl -s "$PR_COMMIT_URL" | jq -r '.commit.message')"
          fi
          echo EOF
        } | tee -a $GITHUB_ENV

    - name: Get kernel submodule ref
      id: kernel-submodule
      run: echo "ref=$(git ls-tree HEAD | awk '$4 == "agnos-kernel-sdm845"' | awk '{print $3}')" | tee -a $GITHUB_OUTPUT

    - name: ccache
      uses: hendrikmuhs/ccache-action@c92f40bee50034e84c763e33b317c77adaa81c92
      with:
        key: kernel-${{ steps.kernel-submodule.outputs.ref }}
        restore-keys: kernel-

    - name: Build kernel
      run: ./build_kernel.sh

    - name: Upload artifact boot.img
      uses: actions/upload-artifact@v4
      if: "contains(env.LAST_COMMIT_MESSAGE, '[upload]')"
      with:
        name: boot.img
        path: output/boot.img

    - name: Upload artifact kernel modules
      uses: actions/upload-artifact@v4
      if: "contains(env.LAST_COMMIT_MESSAGE, '[upload]')"
      with:
        name: kernel-modules
        path: output/*.ko

    - name: Build system
      run: ./build_system.sh

    - name: Upload artifact system.img
      uses: actions/upload-artifact@v4
      if: "contains(env.LAST_COMMIT_MESSAGE, '[upload]')"
      with:
        name: system.img
        path: output/system.img

    - name: Package and OTA push
      if: "contains(env.LAST_COMMIT_MESSAGE, '[release]')"
      env:
        AGNOS_UPDATE_URL: https://openpilot.blob.core.windows.net/agnosupdate-ci/${{ github.run_id }}
        # TODO: switch to comma credentials: https://learn.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az-ad-sp-create-for-rbac-examples
        AZURE_CREDENTIALS: '{"appId": "fd6e3414-7fee-4bf3-bd85-dd36d3d03bd2", "password": "Xs-8Q~uaKQaqhGdggDyLmTkwjIa3lNzh2B9AKboR", "tenant": "499a1903-3119-470b-9dd4-d4f436586f25"}'
        # AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        # TODO: remove DATA_ACCOUNT - just for testing
        DATA_ACCOUNT: openpilot
      run: |
        sudo apt-get install -y azure-cli android-sdk-libsparse-utils
        ./scripts/package_ota.py
        az login --service-principal -u $(jq -r .appId <<< $AZURE_CREDENTIALS) -p $(jq -r .password <<< $AZURE_CREDENTIALS) -t $(jq -r .tenant <<< $AZURE_CREDENTIALS)
        ./scripts/ota_push.sh ci ${{ github.run_id }}

    - name: Upload agnos.json
      uses: actions/upload-artifact@v4
      if: "contains(env.LAST_COMMIT_MESSAGE, '[release]')"
      with:
        name: agnos.json
        path: output/ota/ota.json
