name: build

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && github.run_id || github.head_ref || github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: build kernel and system
    runs-on: namespace-profile-arm64-8x16-2004-caching
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        submodules: true

    - name: Get commit message
      run: |
        {
          echo 'LAST_COMMIT_MESSAGE<<EOF'
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "${{ github.event.head_commit.message }}"
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            COMMIT_URL=$(echo "${{ github.event.repository.commits_url }}" | sed "s|{/sha}|/${{ github.sha }}|")
            echo "$(curl -s "$COMMIT_URL" | jq -r '.commit.message')"
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            PR_COMMIT_URL=$(echo "${{ github.event.repository.commits_url }}" | sed "s|{/sha}|/${{ github.event.pull_request.head.sha }}|")
            echo "$(curl -s "$PR_COMMIT_URL" | jq -r '.commit.message')"
          fi
          echo EOF
        } | tee -a $GITHUB_ENV

    - name: Get kernel submodule ref
      id: kernel-submodule
      run: echo "ref=$(git ls-tree HEAD | awk '$4 == "agnos-kernel-sdm845"' | awk '{print $3}')" | tee -a $GITHUB_OUTPUT

    - name: ccache
      uses: hendrikmuhs/ccache-action@c92f40bee50034e84c763e33b317c77adaa81c92
      with:
        key: kernel-${{ steps.kernel-submodule.outputs.ref }}
        restore-keys: kernel-

    - name: Build kernel
      run: ./build_kernel.sh

    - name: Upload artifact boot.img
      uses: actions/upload-artifact@v4
      if: "contains(env.LAST_COMMIT_MESSAGE, '[upload]')"
      with:
        name: boot.img
        path: output/boot.img

    - name: Upload artifact kernel modules
      uses: actions/upload-artifact@v4
      if: "contains(env.LAST_COMMIT_MESSAGE, '[upload]')"
      with:
        name: kernel-modules
        path: output/*.ko

    - name: Build system
      run: ./build_system.sh

    - name: Upload artifact system.img
      uses: actions/upload-artifact@v4
      if: "contains(env.LAST_COMMIT_MESSAGE, '[upload]')"
      with:
        name: system.img
        path: output/system.img

    - name: Azure Login
      uses: azure/login@v2
      if: "contains(env.LAST_COMMIT_MESSAGE, '[release]')"
      with:
        # TODO: switch to comma creds json https://github.com/marketplace/actions/azure-login#creds
        creds: '{"clientSecret": "Hvk8Q~LJ3ozFdGm91x6ygkuDrwBpgA4x50kKabOL", "subscriptionId": "4338b670-e37b-4212-8b72-eec520b88051", "tenantId": "499a1903-3119-470b-9dd4-d4f436586f25", "clientId": "6316da0d-22c2-4141-bde6-5674553be414"}'
        # creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Package and OTA push
      if: "contains(env.LAST_COMMIT_MESSAGE, '[release]')"
      env:
        AGNOS_UPDATE_URL: https://openpilot.blob.core.windows.net/agnosupdate-ci/${{ github.run_id }}
        # TODO: remove DATA_ACCOUNT - just for testing
        DATA_ACCOUNT: openpilot
      run: |
        ./scripts/package_ota.py
        ./scripts/ota_push.sh ci ${{ github.run_id }}

    - name: Upload agnos.json
      uses: actions/upload-artifact@v4
      if: "contains(env.LAST_COMMIT_MESSAGE, '[release]')"
      with:
        name: agnos.json
        path: output/ota/ota.json
