name: build

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && github.run_id || github.head_ref || github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
      with:
        filter: blob:none
    - name: checkout submodule ref
      run: git submodule update --init --filter blob:none agnos-kernel-sdm845

    - run: ./build_kernel.sh
    - uses: actions/upload-artifact@v4
      with:
        name: boot.img
        path: output/boot.img

    - run: ./build_system.sh
    - uses: actions/upload-artifact@v4
      with:
        name: system.img
        path: output/system.img
