name: build

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
      with:
        filter: blob:none

    - name: checkout submodule ref
      run: git submodule update --init --filter blob:none agnos-kernel-sdm845

    - run: ./build_kernel.sh
    - run: ./build_system.sh
